//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.SessionService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SessionService.ISessionService")]
    public interface ISessionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionService/Login", ReplyAction="http://tempuri.org/ISessionService/LoginResponse")]
        Data.Session Login(Data.Utils.LoginWrapper credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionService/Login", ReplyAction="http://tempuri.org/ISessionService/LoginResponse")]
        System.Threading.Tasks.Task<Data.Session> LoginAsync(Data.Utils.LoginWrapper credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionService/Delete", ReplyAction="http://tempuri.org/ISessionService/DeleteResponse")]
        void Delete(string userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionService/Delete", ReplyAction="http://tempuri.org/ISessionService/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(string userid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISessionServiceChannel : UI.SessionService.ISessionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SessionServiceClient : System.ServiceModel.ClientBase<UI.SessionService.ISessionService>, UI.SessionService.ISessionService {
        
        public SessionServiceClient() {
        }
        
        public SessionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SessionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SessionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SessionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Data.Session Login(Data.Utils.LoginWrapper credentials) {
            return base.Channel.Login(credentials);
        }
        
        public System.Threading.Tasks.Task<Data.Session> LoginAsync(Data.Utils.LoginWrapper credentials) {
            return base.Channel.LoginAsync(credentials);
        }
        
        public void Delete(string userid) {
            base.Channel.Delete(userid);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(string userid) {
            return base.Channel.DeleteAsync(userid);
        }
    }
}
