// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Countries_Cities_UserCity_fix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Countries_Cities_UserCity_fix));
        
        string IMigrationMetadata.Id
        {
            get { return "201511261114369_Countries_Cities_UserCity_fix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
