// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Meetup_cycle_fix_again : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Meetup_cycle_fix_again));
        
        string IMigrationMetadata.Id
        {
            get { return "201512041646116_Meetup_cycle_fix_again"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
