// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MeetUp_cascade_fix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MeetUp_cascade_fix));
        
        string IMigrationMetadata.Id
        {
            get { return "201512041637364_MeetUp_cascade_fix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
