// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class User_City_fix_attempt_n2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(User_City_fix_attempt_n2));
        
        string IMigrationMetadata.Id
        {
            get { return "201512030932247_User_City_fix_attempt_n2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
